version: "0.3.0"

.cargo_all: !inline &cargo_all |-
  set -e

  cargo build --all-features
  cargo build --release --all-features
  cargo doc --no-deps --document-private-items --workspace
  cargo test --all
  # cargo +nightly fmt --all -- --check

hooks:
  "pre-commit": # pre-commit hook
    - command: *cargo_all
  "pre-push": # pre-push hook
    - command: *cargo_all
